version: "3.5"
services:

  
  api-server:
    container_name: leafeon_api_server
    expose: 
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - docker-net


networks:
  docker-net:
    driver: bridge
